### PR TITLE
ADD: Changes to run in ROS2 Humble on Ubuntu 22.04

### PR DESCRIPTION
**Pull request by T-K-233**

### CODE REVIEW

**Comment by fan-ziqi** [comment]
I will try to modify the code to be compatible with 20.04 and 22.04

**Comment by fan-ziqi** [comment]
I have tested it on 20.04 without any problems. Could you please test it on 24.04

**Comment by fan-ziqi** [comment]
After that, please add your name in `Contributors` of `CONTRIBUTORS.md`

**Comment by T-K-233** [comment]
Verified in Ubuntu 22.04. It runs all good!

I will also try Ubuntu 24.04, but I think this will be a stretch goal, and will deal with it in another PR.

**Comment by fan-ziqi** [comment]
Thank you for your contribution to this project!

**Pull request merged**
